{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=34359): Max retries exceeded with url: /session/bde96db8-d792-4b6a-b32c-4e8704d783f9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49dba4370>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_yandex_search","uid":"84bc634a2f65f26b","parentUid":"e136b7bc23877c492cd8d96ac9160e1a","status":"broken","time":{"start":1676278541541,"stop":1676278541543,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"e136b7bc23877c492cd8d96ac9160e1a"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=34359): Max retries exceeded with url: /session/bde96db8-d792-4b6a-b32c-4e8704d783f9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49d8e2380>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_mail_search","uid":"c84807f3113c33a4","parentUid":"0faeb273d9aae680ec7913fbc34a8358","status":"broken","time":{"start":1676278541757,"stop":1676278541759,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0faeb273d9aae680ec7913fbc34a8358"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}