{"8f2ecf30b81961a8b55483fb1bb61617":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"3730c01004ff6634","reportUrl":"https://Yuriyvas.github.io/pythonProject5/11//#testresult/3730c01004ff6634","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52721): Max retries exceeded with url: /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c26e410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1676284093505,"stop":1676284093507,"duration":2}},{"uid":"c84807f3113c33a4","reportUrl":"https://Yuriyvas.github.io/pythonProject5/10//#testresult/c84807f3113c33a4","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=34359): Max retries exceeded with url: /session/bde96db8-d792-4b6a-b32c-4e8704d783f9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49d8e2380>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1676278541757,"stop":1676278541759,"duration":2}},{"uid":"b9b94ad1e03345fc","reportUrl":"https://Yuriyvas.github.io/pythonProject5/6//#testresult/b9b94ad1e03345fc","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55d62232b303 <unknown>\n#1 0x55d6220ffd37 <unknown>\n#2 0x55d622128157 <unknown>\n#3 0x55d622124330 <unknown>\n#4 0x55d6221654a6 <unknown>\n#5 0x55d62215c753 <unknown>\n#6 0x55d62212fa14 <unknown>\n#7 0x55d622130b7e <unknown>\n#8 0x55d62237a32e <unknown>\n#9 0x55d62237dc0e <unknown>\n#10 0x55d622360610 <unknown>\n#11 0x55d62237ec23 <unknown>\n#12 0x55d622352545 <unknown>\n#13 0x55d62239f6a8 <unknown>\n#14 0x55d62239f836 <unknown>\n#15 0x55d6223bad13 <unknown>\n#16 0x7f933c266b43 <unknown>","time":{"start":1676144196945,"stop":1676144196945,"duration":0}},{"uid":"2f243a0692c04791","reportUrl":"https://Yuriyvas.github.io/pythonProject5/5//#testresult/2f243a0692c04791","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55cff01b6303 <unknown>\n#1 0x55cfeff8ad37 <unknown>\n#2 0x55cfeffb3157 <unknown>\n#3 0x55cfeffaf330 <unknown>\n#4 0x55cfefff04a6 <unknown>\n#5 0x55cfeffe7753 <unknown>\n#6 0x55cfeffbaa14 <unknown>\n#7 0x55cfeffbbb7e <unknown>\n#8 0x55cff020532e <unknown>\n#9 0x55cff0208c0e <unknown>\n#10 0x55cff01eb610 <unknown>\n#11 0x55cff0209c23 <unknown>\n#12 0x55cff01dd545 <unknown>\n#13 0x55cff022a6a8 <unknown>\n#14 0x55cff022a836 <unknown>\n#15 0x55cff0245d13 <unknown>\n#16 0x7f2e2f424b43 <unknown>","time":{"start":1676143939065,"stop":1676143939065,"duration":0}}]},"dc8c3596712c4e4db968f3d10d3ba413":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":2,"unknown":0,"total":4},"items":[{"uid":"4b5bd857b82db164","reportUrl":"https://Yuriyvas.github.io/pythonProject5/11//#testresult/4b5bd857b82db164","status":"passed","time":{"start":1676284091542,"stop":1676284092631,"duration":1089}},{"uid":"d478d832aaac205a","reportUrl":"https://Yuriyvas.github.io/pythonProject5/10//#testresult/d478d832aaac205a","status":"passed","time":{"start":1676278539885,"stop":1676278540985,"duration":1100}},{"uid":"1797728e22c2183e","reportUrl":"https://Yuriyvas.github.io/pythonProject5/6//#testresult/1797728e22c2183e","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x558432a16303 <unknown>\n#1 0x5584327ead37 <unknown>\n#2 0x558432813157 <unknown>\n#3 0x55843280f330 <unknown>\n#4 0x5584328504a6 <unknown>\n#5 0x558432847753 <unknown>\n#6 0x55843281aa14 <unknown>\n#7 0x55843281bb7e <unknown>\n#8 0x558432a6532e <unknown>\n#9 0x558432a68c0e <unknown>\n#10 0x558432a4b610 <unknown>\n#11 0x558432a69c23 <unknown>\n#12 0x558432a3d545 <unknown>\n#13 0x558432a8a6a8 <unknown>\n#14 0x558432a8a836 <unknown>\n#15 0x558432aa5d13 <unknown>\n#16 0x7f38ef039b43 <unknown>","time":{"start":1676144194077,"stop":1676144194077,"duration":0}},{"uid":"2c7e0bf82152587c","reportUrl":"https://Yuriyvas.github.io/pythonProject5/5//#testresult/2c7e0bf82152587c","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x561b15f80303 <unknown>\n#1 0x561b15d54d37 <unknown>\n#2 0x561b15d7d157 <unknown>\n#3 0x561b15d79330 <unknown>\n#4 0x561b15dba4a6 <unknown>\n#5 0x561b15db1753 <unknown>\n#6 0x561b15d84a14 <unknown>\n#7 0x561b15d85b7e <unknown>\n#8 0x561b15fcf32e <unknown>\n#9 0x561b15fd2c0e <unknown>\n#10 0x561b15fb5610 <unknown>\n#11 0x561b15fd3c23 <unknown>\n#12 0x561b15fa7545 <unknown>\n#13 0x561b15ff46a8 <unknown>\n#14 0x561b15ff4836 <unknown>\n#15 0x561b1600fd13 <unknown>\n#16 0x7f7fa1ec6b43 <unknown>","time":{"start":1676143934216,"stop":1676143934216,"duration":0}}]},"5724252c070c0109b41fc65514d182e5":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"4d0771bf17bb4b6f","reportUrl":"https://Yuriyvas.github.io/pythonProject5/11//#testresult/4d0771bf17bb4b6f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52721): Max retries exceeded with url: /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c530370>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1676284093301,"stop":1676284093304,"duration":3}},{"uid":"84bc634a2f65f26b","reportUrl":"https://Yuriyvas.github.io/pythonProject5/10//#testresult/84bc634a2f65f26b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=34359): Max retries exceeded with url: /session/bde96db8-d792-4b6a-b32c-4e8704d783f9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd49dba4370>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1676278541541,"stop":1676278541543,"duration":2}},{"uid":"6efcff065ebbcd1a","reportUrl":"https://Yuriyvas.github.io/pythonProject5/6//#testresult/6efcff065ebbcd1a","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x563085385303 <unknown>\n#1 0x563085159d37 <unknown>\n#2 0x563085182157 <unknown>\n#3 0x56308517e330 <unknown>\n#4 0x5630851bf4a6 <unknown>\n#5 0x5630851b6753 <unknown>\n#6 0x563085189a14 <unknown>\n#7 0x56308518ab7e <unknown>\n#8 0x5630853d432e <unknown>\n#9 0x5630853d7c0e <unknown>\n#10 0x5630853ba610 <unknown>\n#11 0x5630853d8c23 <unknown>\n#12 0x5630853ac545 <unknown>\n#13 0x5630853f96a8 <unknown>\n#14 0x5630853f9836 <unknown>\n#15 0x563085414d13 <unknown>\n#16 0x7f64b4263b43 <unknown>","time":{"start":1676144196290,"stop":1676144196290,"duration":0}},{"uid":"a1b85fdbe8ca3d94","reportUrl":"https://Yuriyvas.github.io/pythonProject5/5//#testresult/a1b85fdbe8ca3d94","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55a6f0a01303 <unknown>\n#1 0x55a6f07d5d37 <unknown>\n#2 0x55a6f07fe157 <unknown>\n#3 0x55a6f07fa330 <unknown>\n#4 0x55a6f083b4a6 <unknown>\n#5 0x55a6f0832753 <unknown>\n#6 0x55a6f0805a14 <unknown>\n#7 0x55a6f0806b7e <unknown>\n#8 0x55a6f0a5032e <unknown>\n#9 0x55a6f0a53c0e <unknown>\n#10 0x55a6f0a36610 <unknown>\n#11 0x55a6f0a54c23 <unknown>\n#12 0x55a6f0a28545 <unknown>\n#13 0x55a6f0a756a8 <unknown>\n#14 0x55a6f0a75836 <unknown>\n#15 0x55a6f0a90d13 <unknown>\n#16 0x7faffb80bb43 <unknown>","time":{"start":1676143938329,"stop":1676143938329,"duration":0}}]}}