{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52721): Max retries exceeded with url: /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c530370>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_yandex_search","uid":"4d0771bf17bb4b6f","parentUid":"f0828388c54095afa47c0fb47131bf3a","status":"broken","time":{"start":1676284093301,"stop":1676284093304,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"f0828388c54095afa47c0fb47131bf3a"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52721): Max retries exceeded with url: /session/167b9e64-34a4-4f19-b862-a36ae6dcf70b/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa26c26e410>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_mail_search","uid":"3730c01004ff6634","parentUid":"35931f0fe7c52ed82cb29eec4e6855fc","status":"broken","time":{"start":1676284093505,"stop":1676284093507,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"35931f0fe7c52ed82cb29eec4e6855fc"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}